### ISSUE TITLE
Linter can't handle numeric headers.

### ISSUE THREAD

**Issue by marcosfpr** [alandefreitas/small#8]
**Bug category**

- [ ] *bug - compilation error*
- [ ] *bug - compilation warning*
- [ ] *bug - runtime error*
- [ ] *bug - runtime warning*
- [X] *bug - logic error*

**Describe the bug**

As discussed here #7, the linter has issues when handling numeric headers. For example, if we have the header ``SMALL_UTF8_STRING_H``, the linter will change it to ``SMALL_STRING_H8_STRING_H``, which is considered unexpected behavior.

A possibly solution to that issue is refactoring the regex at https://github.com/marcosfpr/small/blob/c4e64a5f3114d610524342914c6c18e262176c27/dev-tools/linter/main.cpp#L213.

**Platform**

- [x] *cross-platform issue - linux*
- [x] *cross-platform issue - windows*
- [x] *cross-platform issue - macos*

**Environment Details:**
 - OS: 
 - OS Version: 
 - Compiler:
 - Compiler version:

**Additional context**

**Comment by alandefreitas** [comment]
While at it, we could just look at the C++ grammar for valid chars in macros and filter all of these already.
